### PR TITLE
county support

### PR DESCRIPTION
**Pull request by pjaudiomv**
@paulnagle  ref #7 this is set to disabled (0) by default

### CODE REVIEW

**Comment by radius314** [comment]
looks like there are some tabbing related issues on your system cause extreme diffs on the javascript file.  also some of the alignments are off.

**Comment by radius314** [comment]
https://editorconfig.org

**Comment by radius314** [comment]
You may want to update the contribution guidelines https://github.com/radius314/crouton/blob/master/contribute.md

**Comment by pjaudiomv** [comment]
the large diff on the js is must just be because the amount of changes. as the formatting is to the T

**Comment by radius314** [comment]
it's not, because if i ignore whitespace changes it shows up just fine 

https://github.com/radius314/crouton/pull/11/files?utf8=✓&diff=unified&w=1

**Comment by radius314** [comment]
it could be that encoding changed on the files?

**Comment by pjaudiomv** [comment]
maybe, i closed this when i rebased but not sure how to repopen so just creating new pr

**Comment by pjaudiomv** [comment]
i think you may have been right about the encoding

**Pull request closed without merging**
